CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE Organizations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workgroups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    enabled    BOOLEAN                                 NOT NULL DEFAULT FALSE,
--     organization_id INT NOT NULL,
    created_at TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP
--     FOREIGN KEY (organization_id) REFERENCES Organizations (id)
);

CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    workgroup_id BIGINT NOT NULL,
    role_id      BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users (id),
    FOREIGN KEY (role_id) REFERENCES Roles (id),
    FOREIGN KEY (workgroup_id) REFERENCES Workgroups (id)
);

INSERT INTO workgroups (id, name)
VALUES (1, 'GLOBAL'),
       (2, 'FINANCE'),
       (3, 'SALES');

INSERT INTO roles (id, name)
VALUES (1, 'ADMIN'),
       (2, 'REVIEWER'),
       (3, 'USER'),
       (4, 'GUEST');

INSERT INTO users (id, username, password, email, enabled)
VALUES (1, 'admin', 'admin', 'admin@localhost', true),
       (2, 'reviewer', 'reviewer', 'reviewer@localhost', true);

INSERT INTO user_roles (user_id, workgroup_id, role_id)
VALUES (1, 1, 1),
       (2, 2, 2),
       (2, 1, 3);
